### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by ekorudi** [LCLR/13-AllWinner-H3#1]
I see your QQ id 1769108832, but i can not install qq on Android. Can i contact you by email or telegram/whatsapp ?

**Comment by LCLR** [comment]
it is ok,i will send the SCH to you with email


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LCLR/13-AllWinner-H3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月31日(星期一) 晚上8:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LCLR/13-AllWinner-H3] Contact  (#1)





 
I see your QQ id 1769108832, but i can not install qq on Android. Can i contact you by email or telegram/whatsapp ?

**Comment by ekorudi** [comment]
my email is ekorudi@gmail.com
